image: Visual Studio 2017 RC

environment:
  SignClientSecret:
    secure: S26+NphAhj/vo5ZdHd/N/4toty3ztdNGmuNdvAB57W1oIVQEHVKqAVuhTD8B9ATy
     
install: 
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
  - cmd: nuget install SignClient -Version 0.5.0-beta4 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
    
build_script:
  - cmd: '"%ProgramFiles(x86)%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\sn.exe" -Vr *'
  - cmd: '"%ProgramFiles(x86)%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\sn.exe" -Vr *'
  - cmd: msbuild Zeroconf\Zeroconf.csproj /t:restore /p:Configuration=Release
  - cmd: msbuild Zeroconf\Zeroconf.csproj /t:pack /p:Configuration=Release
  
after_build:
  - cmd: move Zeroconf\bin\Release\*.nupkg .
  - ps: '.\SignClient\SignPackage.ps1'

artifacts:
  - path: '**\*.nupkg'
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/zeroconf/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
